# Generated by Django 4.1.3 on 2022-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/photos', verbose_name='photo'),
        ),
    ]
